name:                heb-haskell
version:             0.1.0.0
github:              "githubuser/heb-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/heb-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- persistent
- aeson
- servant-server
- servant-multipart
- wai
- warp
- bytestring
- text
- http-client
- http-client-tls
- base64-bytestring
- http-types
- transformers
- persistent-postgresql
- resource-pool
- monad-logger
- wai-extra
- split
- containers
- yaml
- mtl
- esqueleto
- extra
- case-insensitive
- utf8-string

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  heb-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - heb-haskell

tests:
  heb-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - heb-haskell
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
